// ============================================================================
// Seed data. PRODUCTION ships EMPTY — items and launch plans are created by
// the coordinators through the UI. Set NEXT_PUBLIC_DEMO_DATA=1 at build time
// to load a rich mock portfolio (for management demos / walkthroughs only).
// NEXT_PUBLIC_DEMO_MODE only controls the role-switcher tabs, not the data.
// Bump SEED_V in domain.ts to force local storage to reseed.
//
// The demo portfolio mirrors how the platform is actually used:
//  - every item is stamped with its owning federal entity (canonical names)
//  - items are distributed over the five demo streams and the workflow states
//    (مسودة، بانتظار ممثل الجهة، بانتظار فريق المسار، معتمد قيد التنفيذ، مكتمل)
//  - ops/strategy items carry «فترة التحويل» in the current «الدفعة - الشهر»
//    format, so the launch-batch pages fill up through auto-placement
//  - services follow the manual placement cycle via launch plans
// ============================================================================
import type { Item } from './domain';
import type { LaunchPlan } from './domain';

export const DEMO_DATA = process.env.NEXT_PUBLIC_DEMO_DATA === '1';

const T = (s: string) => Date.parse(s); // fixed, deterministic timestamps

export function seedItems(): Item[] {
  if (!DEMO_DATA) return [];
  return demoItems();
}

export function seedLaunchPlans(): LaunchPlan[] {
  if (!DEMO_DATA) return [];
  return demoLaunchPlans();
}

function demoItems(): Item[] {
  return [
    // ══════════════ مسار العمليات والدعم المؤسسي ══════════════

    // معتمدة قيد التنفيذ — موزّعة آلياً على الدفعة الأولى
    {
      id: 'd1',
      wf: 'exec',
      type: 'operation',
      title: 'معالجة طلبات الدعم الفني',
      desc: 'استقبال وتشخيص وتوجيه طلبات الدعم الفني آلياً عبر مساعد ذكي.',
      path: 'ops',
      entity: 'وزارة المالية',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      opType: 'عمليات الدعم المؤسسي',
      subActivities: 'استقبال الطلب\nالتشخيص الآلي\nالتوجيه أو الحل الفوري',
      sector: 'قطاع الخدمات المساندة',
      dept: 'إدارة تقنية المعلومات',
      section: 'قسم مكتب الخدمة',
      isAutomated: 'نعم',
      automationSystem: 'نظام إدارة طلبات الدعم',
      automationPct: 55,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'منخفض',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - أكتوبر',
      transformPriority: 'مرتفعة',
      riskLevel: 'منخفضة',
      transformYes: 'نعم',
      notes: '',
      progress: 45,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'قيد التنفيذ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd2',
      wf: 'ent1',
      type: 'operation',
      title: 'التصنيف الآلي للمعاملات الواردة',
      desc: 'تصنيف وتوجيه المعاملات الواردة باستخدام معالجة اللغة الطبيعية.',
      path: 'ops',
      entity: 'وزارة الطاقة والبنية التحتية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      opType: 'العمليات التخصصية',
      subActivities: 'استقبال المعاملات\nتصنيف الموضوع\nالتوجيه للإدارة المعنية',
      sector: 'قطاع الخدمات المؤسسية',
      dept: 'إدارة الاتصال المؤسسي',
      section: 'قسم المراسلات',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام إدارة المراسلات',
      automationPct: 30,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - يناير',
      transformPriority: 'مرتفعة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: '',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة مُعادة بملاحظات (بحاجة إلى استكمال)
    {
      id: 'd3',
      wf: 'draft',
      type: 'operation',
      title: 'تدقيق طلبات الإجازات والبدلات',
      desc: 'تدقيق آلي لطلبات الإجازات والبدلات مع التحقق من السياسات المعتمدة.',
      ret: {
        type: 'info',
        from: 'فريق عمل المسار في المشروع',
        note: 'يرجى تحديد الأنظمة المرتبطة وحجم الطلبات الشهري قبل إعادة الإرسال.',
        gate: 'priority',
      },
      path: 'ops',
      entity: 'وزارة الموارد البشرية والتوطين',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      opType: 'عمليات الدعم المؤسسي',
      subActivities: 'استلام الطلبات\nالتحقق من السياسات\nإصدار القرار',
      sector: 'قطاع الخدمات المساندة',
      dept: 'إدارة الموارد البشرية',
      section: 'قسم شؤون الموظفين',
      isAutomated: 'لا',
      automationSystem: 'لا يوجد',
      automationPct: 0,
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 30% إلى 50%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformScore: 'قابل جزئياً',
      transformPriority: 'منخفضة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: 'بانتظار تحديد الأنظمة المرتبطة.',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد فريق عمل المسار
    {
      id: 'd4',
      wf: 'ent1',
      type: 'operation',
      title: 'إعداد التقارير التشغيلية الدورية',
      desc: 'توليد التقارير التشغيلية الدورية آلياً من أنظمة العمليات.',
      path: 'ops',
      entity: 'وزارة الداخلية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      opType: 'العمليات التخصصية',
      subActivities: 'جمع البيانات التشغيلية\nتحليل المؤشرات\nإصدار التقرير',
      sector: 'قطاع العمليات المركزية',
      dept: 'إدارة العمليات',
      section: 'قسم التقارير',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام التقارير المركزي',
      automationPct: 40,
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - ديسمبر',
      transformPriority: 'متوسطة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: '',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمدة قيد التنفيذ — الدفعة الأولى
    {
      id: 'd5',
      wf: 'exec',
      type: 'operation',
      title: 'متابعة تنفيذ قرارات مجلس الوزراء',
      desc: 'رصد ومتابعة حالة تنفيذ القرارات لدى الجهات عبر مساعد ذكي.',
      path: 'ops',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      opType: 'العمليات التخصصية',
      subActivities: 'تسجيل القرار\nمتابعة الجهات المعنية\nرفع تقارير الإنجاز',
      sector: 'قطاع شؤون مجلس الوزراء',
      dept: 'إدارة متابعة القرارات',
      section: 'قسم المتابعة',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام متابعة القرارات',
      automationPct: 50,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - سبتمبر',
      transformPriority: 'مرتفعة',
      riskLevel: 'منخفضة',
      transformYes: 'نعم',
      notes: '',
      progress: 60,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'قيد التنفيذ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ══════════════ مسار العمل الحكومي الاستراتيجي ══════════════

    // معتمدة قيد التنفيذ — موزّعة آلياً
    {
      id: 'd6',
      wf: 'exec',
      type: 'operation',
      title: 'إعداد تقارير الأداء الحكومي الدورية',
      desc: 'أتمتة إعداد تقارير الأداء الحكومي عبر مساعد ذكاء اصطناعي مساعد.',
      path: 'strategy',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      axis: 'الأداء الحكومي',
      subActivities: 'جمع بيانات المؤشرات\nتحليل نتائج الأداء\nصياغة التقرير الدوري',
      sector: 'قطاع الاستراتيجية',
      dept: 'إدارة الأداء الحكومي',
      section: 'قسم التقارير',
      automationLevel: 'مؤتمتة جزئياً',
      automationPct: 40,
      automationSystem: 'نظام إدارة الأداء',
      usageIntensity: '5',
      importance: '5',
      readinessLevel: '4',
      impactScore: '5',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - نوفمبر',
      outputClarity: '4',
      riskLevel: 'منخفض',
      transformYes: 'نعم',
      progress: 30,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd7',
      wf: 'ent1',
      type: 'operation',
      title: 'تحليل اتجاهات السياسات الصحية',
      desc: 'تحليل آلي لاتجاهات السياسات الصحية ومقارنتها بالممارسات العالمية.',
      path: 'strategy',
      entity: 'وزارة الصحة ووقاية المجتمع',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      axis: 'السياسات',
      subActivities: 'رصد السياسات المستجدة\nتحليل الأثر التشريعي',
      sector: 'قطاع السياسات الصحية',
      dept: 'إدارة السياسات العامة',
      section: 'قسم الدراسات',
      automationLevel: 'غير مؤتمتة',
      automationPct: 0,
      automationSystem: 'لا يوجد',
      usageIntensity: '3',
      importance: '4',
      readinessLevel: '3',
      impactScore: '4',
      transformScore: 'قابل جزئياً',
      transformPeriod: 'الدفعة الثالثة - مارس',
      outputClarity: '3',
      riskLevel: 'متوسط',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمدة قيد التنفيذ — الدفعة الثانية
    {
      id: 'd8',
      wf: 'exec',
      type: 'operation',
      title: 'رصد مؤشرات التنافسية العالمية',
      desc: 'رصد وتحليل مواقع الدولة في مؤشرات التنافسية العالمية آلياً.',
      path: 'strategy',
      entity: 'وزارة الاقتصاد والسياحة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      axis: 'التنافسية',
      subActivities: 'جمع بيانات المؤشرات الدولية\nتحليل الفجوات\nاقتراح مبادرات التحسين',
      sector: 'قطاع الاقتصاد',
      dept: 'إدارة التنافسية',
      section: 'قسم المؤشرات',
      automationLevel: 'مؤتمتة جزئياً',
      automationPct: 35,
      automationSystem: 'منصة المؤشرات الوطنية',
      usageIntensity: '4',
      importance: '5',
      readinessLevel: '4',
      impactScore: '4',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - فبراير',
      outputClarity: '4',
      riskLevel: 'منخفض',
      transformYes: 'نعم',
      progress: 20,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة — غير قابلة للتحول (لا تنطبق عليها فترة التحويل)
    {
      id: 'd9',
      wf: 'draft',
      type: 'operation',
      title: 'مراجعة الالتزامات المناخية الدولية',
      desc: 'مراجعة دورية للالتزامات المناخية ومواءمتها مع الاتفاقيات الدولية.',
      path: 'strategy',
      entity: 'وزارة التغير المناخي والبيئة',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      axis: 'السياسات',
      subActivities: 'حصر الالتزامات\nمراجعة الاتفاقيات',
      sector: 'قطاع التغير المناخي',
      dept: 'إدارة الاتفاقيات الدولية',
      section: 'قسم الالتزامات',
      automationLevel: 'غير مؤتمتة',
      automationPct: 0,
      automationSystem: 'لا يوجد',
      usageIntensity: '2',
      importance: '3',
      readinessLevel: '2',
      impactScore: '2',
      transformScore: 'غير قابل',
      outputClarity: '2',
      riskLevel: 'عالي',
      transformYes: 'لا',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار الخدمات الحكومية ══════════════

    // معتمدة قيد التنفيذ ضمن خطة إطلاق الدفعة الأولى
    {
      id: 'd10',
      wf: 'exec',
      type: 'service',
      title: 'خدمة تجديد الرخص التجارية الذكية',
      desc: 'تجديد فوري للرخص التجارية عبر مساعد محادثة ذكي.',
      path: 'services',
      entity: 'وزارة الاقتصاد والسياحة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      complexity: 'منخفض',
      subService: 'تجديد رخصة تجارية فورية',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الاقتصاد',
      dept: 'إدارة التسجيل التجاري',
      section: 'قسم الرخص',
      progress: 45,
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp1'],
      endDate: '2026-11-30',
      phases: [],
      launches: [
        {
          title: 'إطلاق الخدمات الاستباقية',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-11-25',
          desc: 'إطلاق الدفعة الأولى من الخدمات الاستباقية للجمهور.',
          status: 'مخطط',
          done: false,
          shared: true,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // معتمدة قيد التنفيذ — الخطة المشتركة نفسها
    {
      id: 'd11',
      wf: 'exec',
      type: 'service',
      title: 'منصة الخدمات الاستباقية',
      desc: 'تقديم الخدمات الحكومية استباقياً بناءً على أحداث حياة المتعامل.',
      path: 'services',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      complexity: 'منخفض',
      subService: 'إشعارات استباقية لأحداث الحياة',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات الحكومية',
      dept: 'إدارة الخدمات الرقمية',
      section: 'قسم تجربة المتعامل',
      progress: 35,
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp1'],
      endDate: '2026-12-20',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مكتملة + مموّلة من اللجنة (تُظهر الترشيح والتمويل والإطلاق المنجز)
    {
      id: 'd12',
      wf: 'exec',
      type: 'service',
      title: 'خدمة الاستعلام الذكي الموحّد',
      desc: 'مساعد محادثة موحّد للاستعلام عن حالة الطلبات عبر القنوات.',
      path: 'services',
      entity: 'وزارة المالية',
      approval: 'معتمد',
      status: 'مكتمل',
      complexity: 'متوسط',
      subService: 'الاستعلام عن حالة الطلب',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات المؤسسية',
      dept: 'إدارة خدمة المتعاملين',
      section: 'قسم القنوات الرقمية',
      progress: 100,
      budget: '1,500,000 درهم',
      scopeOfWork: 'بناء المساعد الموحّد وربطه بأنظمة الطلبات عبر القنوات الرقمية.',
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp5'],
      endDate: '2026-09-15',
      nom: {
        by: 'فريق عمل المسار في المشروع',
        role: 'فريق عمل المسار في المشروع',
        path: 'services',
        at: T('2026-06-20T09:00:00'),
      },
      funded: { by: 'اللجنة الوطنية', at: T('2026-06-25T13:30:00'), direct: false },
      phases: [],
      launches: [
        {
          title: 'إطلاق الاستعلام الذكي',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-09-10',
          desc: '',
          status: 'تم الإطلاق',
          done: true,
          doneAt: T('2026-09-10T10:00:00'),
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام الوكيلي', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'مكتمل', newDate: '', reason: '' },
      ],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd13',
      wf: 'ent1',
      type: 'service',
      title: 'إصدار شهادة حسن السيرة والسلوك الفوري',
      desc: 'إصدار فوري للشهادة بعد التحقق الآلي من السجلات.',
      path: 'services',
      entity: 'وزارة الداخلية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      complexity: 'متوسط',
      subService: 'إصدار شهادة حسن السيرة والسلوك',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'متوسط',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات الأمنية',
      dept: 'إدارة الأدلة الجنائية',
      section: 'قسم الشهادات',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة مُعادة بملاحظات
    {
      id: 'd14',
      wf: 'draft',
      type: 'service',
      title: 'معادلة الشهادات الدراسية الذكية',
      desc: 'معادلة آلية للشهادات الدراسية الصادرة من الخارج.',
      ret: {
        type: 'info',
        from: 'فريق عمل المسار في المشروع',
        note: 'يرجى إرفاق حجم الطلبات السنوي وقائمة الجهات التعليمية المعتمدة.',
        gate: 'priority',
      },
      path: 'services',
      entity: 'وزارة التربية والتعليم',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      complexity: 'مرتفع',
      subService: 'معادلة شهادة دراسية',
      usageIntensity: 'متوسطة',
      readinessLevel: 'متوسط',
      transformYes: 'نعم',
      sector: 'قطاع التعليم',
      dept: 'إدارة المعادلات',
      section: 'قسم الشهادات الأجنبية',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار بناء القدرات والتدريب ══════════════

    // معتمد قيد التنفيذ
    {
      id: 'd15',
      wf: 'exec',
      type: 'operation',
      title: 'برنامج قيادات الذكاء الاصطناعي المساعد',
      desc: 'تأهيل القيادات الحكومية على توظيف المساعدين الذكيين في اتخاذ القرار.',
      path: 'capacity',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تصميم الحقائب التدريبية\nتنفيذ الورش القيادية\nقياس أثر التدريب',
      sector: 'قطاع تنمية القدرات',
      dept: 'إدارة التدريب الحكومي',
      section: 'قسم البرامج القيادية',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 55,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd16',
      wf: 'ent1',
      type: 'operation',
      title: 'تأهيل منسقي الجهات على أدوات المساعدين',
      desc: 'برنامج تدريبي عملي لمنسقي المسارات على بناء المساعدين واستخدامهم.',
      path: 'capacity',
      entity: 'وزارة الموارد البشرية والتوطين',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      subActivities: 'تحديد الفئات المستهدفة\nتنفيذ المعسكرات التدريبية\nإصدار الشهادات',
      sector: 'قطاع تنمية الموارد البشرية',
      dept: 'إدارة التدريب والتطوير',
      section: 'قسم البرامج التقنية',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'منخفض',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمد قيد التنفيذ — جهة أكاديمية
    {
      id: 'd17',
      wf: 'exec',
      type: 'operation',
      title: 'مختبر تطبيقات المساعدين الجامعي',
      desc: 'مختبر تطبيقي لتدريب الطلبة على بناء حالات استخدام حكومية حقيقية.',
      path: 'capacity',
      entity: 'جامعة الإمارات العربية المتحدة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تجهيز بيئة المختبر\nبناء الشراكات مع الجهات\nتشغيل الدفعة الأولى من المشاريع',
      sector: 'قطاع التعليم العالي',
      dept: 'كلية تقنية المعلومات',
      section: 'قسم الذكاء الاصطناعي',
      usageIntensity: 'منخفضة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 25,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار تقنيات الذكاء الاصطناعي والبيانات ══════════════

    // معتمد قيد التنفيذ — بنية تحتية وطنية
    {
      id: 'd18',
      wf: 'exec',
      type: 'operation',
      title: 'المنصة الوطنية للنماذج اللغوية الحكومية',
      desc: 'بنية موحّدة لاستضافة النماذج اللغوية وتشغيل مساعدي الجهات عليها.',
      path: 'tech',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تجهيز البنية السحابية\nربط الجهات بالمنصة\nتفعيل ضوابط الاستخدام',
      sector: 'قطاع التقنيات الحكومية',
      dept: 'إدارة المنصات الوطنية',
      section: 'قسم الذكاء الاصطناعي',
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'مرتفع',
      transformYes: 'نعم',
      progress: 40,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد فريق عمل المسار
    {
      id: 'd19',
      wf: 'ent1',
      type: 'operation',
      title: 'إطار حوكمة بيانات المساعدين',
      desc: 'إطار موحّد لتصنيف البيانات وضوابط وصول المساعدين الذكيين إليها.',
      path: 'tech',
      entity: 'مصرف الإمارات العربية المتحدة المركزي',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      subActivities: 'تصنيف مستويات البيانات\nصياغة ضوابط الوصول\nاعتماد الإطار ونشره',
      sector: 'قطاع الرقابة المالية',
      dept: 'إدارة أمن المعلومات',
      section: 'قسم حوكمة البيانات',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'مرتفع',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمد قيد التنفيذ
    {
      id: 'd20',
      wf: 'exec',
      type: 'operation',
      title: 'مصنّف الوثائق الصناعية الآلي',
      desc: 'نموذج لتصنيف واستخلاص بيانات الوثائق الصناعية والتراخيص آلياً.',
      path: 'tech',
      entity: 'وزارة الصناعة والتكنولوجيا المتقدمة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'بناء مجموعة البيانات\nتدريب النموذج\nالربط بنظام التراخيص',
      sector: 'قطاع الصناعة',
      dept: 'إدارة التحول الرقمي',
      section: 'قسم البيانات',
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 15,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },
  ];
}

function demoLaunchPlans(): LaunchPlan[] {
  return [
    {
      id: 'lp1',
      batch: 'إطلاق الدفعة الأولى',
      title: 'إطلاق الخدمات الاستباقية',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-11-25',
      desc: 'إطلاق الدفعة الأولى من الخدمات الاستباقية للجمهور.',
      scope: 'تحويل مجموعة الخدمات الاستباقية الأولى وربطها بمحرك أحداث الحياة.',
      budget: '3,500,000 درهم',
      launchBudget: '450,000 درهم',
    },
    {
      id: 'lp2',
      batch: 'إطلاق الدفعة الثانية',
      title: 'حزمة خدمات المتعاملين الثانية',
      ltype: 'إعلان رسمي',
      date: '2027-01-20',
      desc: '',
      scope: 'إطلاق الحزمة الثانية من خدمات المتعاملين المحوّلة على مستوى الجهات.',
      budget: '2,200,000 درهم',
      launchBudget: '180,000 درهم',
    },
    {
      id: 'lp5',
      batch: 'إطلاق الدفعة الأولى',
      title: 'إطلاق الاستعلام الذكي',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-09-10',
      desc: '',
      scope: 'إطلاق مساعد الاستعلام الموحّد عبر القنوات.',
      budget: '1,500,000 درهم',
      launchBudget: '120,000 درهم',
    },
  ];
}
