// ============================================================================
// Seed data. PRODUCTION ships EMPTY — items and launch plans are created by
// the coordinators through the UI. Set NEXT_PUBLIC_DEMO_DATA=1 at build time
// to load a rich mock portfolio (for management demos / walkthroughs only).
// NEXT_PUBLIC_DEMO_MODE only controls the role-switcher tabs, not the data.
// Bump SEED_V in domain.ts to force local storage to reseed.
//
// The demo portfolio mirrors how the platform is actually used:
//  - every item is stamped with its owning federal entity (canonical names)
//  - items are distributed over the five demo streams and the workflow states
//    (مسودة، بانتظار ممثل الجهة، بانتظار فريق المسار، معتمد قيد التنفيذ، مكتمل)
//  - ops/strategy items carry «فترة التحويل» in the current «الدفعة - الشهر»
//    format, so the launch-batch pages fill up through auto-placement
//  - services follow the manual placement cycle via launch plans
// ============================================================================
import type { Item, LaunchPlan, ProjDef, ProjForm } from './domain';
import type { MocaEntry, MocaUseCase } from './moca';

// mirrors ChangeLogEntry in store.ts (declared there, not exported)
export type SeedChangeLogEntry = { at: number; by: string; role: string; action: string; target?: string; note?: string };

export const DEMO_DATA = process.env.NEXT_PUBLIC_DEMO_DATA === '1';

const T = (s: string) => Date.parse(s); // fixed, deterministic timestamps

export function seedItems(): Item[] {
  if (!DEMO_DATA) return [];
  return demoItems();
}

export function seedLaunchPlans(): LaunchPlan[] {
  if (!DEMO_DATA) return [];
  return demoLaunchPlans();
}

function demoItems(): Item[] {
  return [
    // ══════════════ مسار العمليات والدعم المؤسسي ══════════════

    // معتمدة قيد التنفيذ — موزّعة آلياً على الدفعة الأولى
    {
      id: 'd1',
      wf: 'exec',
      type: 'operation',
      title: 'معالجة طلبات الدعم الفني',
      desc: 'استقبال وتشخيص وتوجيه طلبات الدعم الفني آلياً عبر مساعد ذكي.',
      path: 'ops',
      entity: 'وزارة المالية',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      opType: 'عمليات الدعم المؤسسي',
      subActivities: 'استقبال الطلب\nالتشخيص الآلي\nالتوجيه أو الحل الفوري',
      sector: 'قطاع الخدمات المساندة',
      dept: 'إدارة تقنية المعلومات',
      section: 'قسم مكتب الخدمة',
      isAutomated: 'نعم',
      automationSystem: 'نظام إدارة طلبات الدعم',
      automationPct: 55,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'منخفض',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - أكتوبر',
      transformPriority: 'مرتفعة',
      riskLevel: 'منخفضة',
      transformYes: 'نعم',
      notes: '',
      progress: 45,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام المساعد', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'قيد التنفيذ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd2',
      wf: 'ent1',
      type: 'operation',
      title: 'التصنيف الآلي للمعاملات الواردة',
      desc: 'تصنيف وتوجيه المعاملات الواردة باستخدام معالجة اللغة الطبيعية.',
      path: 'ops',
      entity: 'وزارة الطاقة والبنية التحتية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      opType: 'العمليات التخصصية',
      subActivities: 'استقبال المعاملات\nتصنيف الموضوع\nالتوجيه للإدارة المعنية',
      sector: 'قطاع الخدمات المؤسسية',
      dept: 'إدارة الاتصال المؤسسي',
      section: 'قسم المراسلات',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام إدارة المراسلات',
      automationPct: 30,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - يناير',
      transformPriority: 'مرتفعة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: '',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة مُعادة بملاحظات (بحاجة إلى استكمال)
    {
      id: 'd3',
      wf: 'draft',
      type: 'operation',
      title: 'تدقيق طلبات الإجازات والبدلات',
      desc: 'تدقيق آلي لطلبات الإجازات والبدلات مع التحقق من السياسات المعتمدة.',
      ret: {
        type: 'info',
        from: 'فريق عمل المسار في المشروع',
        note: 'يرجى تحديد الأنظمة المرتبطة وحجم الطلبات الشهري قبل إعادة الإرسال.',
        gate: 'priority',
      },
      path: 'ops',
      entity: 'وزارة الموارد البشرية والتوطين',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      opType: 'عمليات الدعم المؤسسي',
      subActivities: 'استلام الطلبات\nالتحقق من السياسات\nإصدار القرار',
      sector: 'قطاع الخدمات المساندة',
      dept: 'إدارة الموارد البشرية',
      section: 'قسم شؤون الموظفين',
      isAutomated: 'لا',
      automationSystem: 'لا يوجد',
      automationPct: 0,
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 30% إلى 50%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformScore: 'قابل جزئياً',
      transformPriority: 'منخفضة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: 'بانتظار تحديد الأنظمة المرتبطة.',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد فريق عمل المسار
    {
      id: 'd4',
      wf: 'ent1',
      type: 'operation',
      title: 'إعداد التقارير التشغيلية الدورية',
      desc: 'توليد التقارير التشغيلية الدورية آلياً من أنظمة العمليات.',
      path: 'ops',
      entity: 'وزارة الداخلية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      opType: 'العمليات التخصصية',
      subActivities: 'جمع البيانات التشغيلية\nتحليل المؤشرات\nإصدار التقرير',
      sector: 'قطاع العمليات المركزية',
      dept: 'إدارة العمليات',
      section: 'قسم التقارير',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام التقارير المركزي',
      automationPct: 40,
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - ديسمبر',
      transformPriority: 'متوسطة',
      riskLevel: 'متوسطة',
      transformYes: 'نعم',
      notes: '',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمدة قيد التنفيذ — الدفعة الأولى
    {
      id: 'd5',
      wf: 'exec',
      type: 'operation',
      title: 'متابعة تنفيذ قرارات مجلس الوزراء',
      desc: 'رصد ومتابعة حالة تنفيذ القرارات لدى الجهات عبر مساعد ذكي.',
      path: 'ops',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      opType: 'العمليات التخصصية',
      subActivities: 'تسجيل القرار\nمتابعة الجهات المعنية\nرفع تقارير الإنجاز',
      sector: 'قطاع شؤون مجلس الوزراء',
      dept: 'إدارة متابعة القرارات',
      section: 'قسم المتابعة',
      isAutomated: 'جزئياً',
      automationSystem: 'نظام متابعة القرارات',
      automationPct: 50,
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - سبتمبر',
      transformPriority: 'مرتفعة',
      riskLevel: 'منخفضة',
      transformYes: 'نعم',
      notes: '',
      progress: 60,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام المساعد', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'قيد التنفيذ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // ══════════════ مسار العمل الحكومي الاستراتيجي ══════════════

    // معتمدة قيد التنفيذ — موزّعة آلياً
    {
      id: 'd6',
      wf: 'exec',
      type: 'operation',
      title: 'إعداد تقارير الأداء الحكومي الدورية',
      desc: 'أتمتة إعداد تقارير الأداء الحكومي عبر مساعد ذكاء اصطناعي مساعد.',
      path: 'strategy',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      axis: 'الأداء الحكومي',
      subActivities: 'جمع بيانات المؤشرات\nتحليل نتائج الأداء\nصياغة التقرير الدوري',
      sector: 'قطاع الاستراتيجية',
      dept: 'إدارة الأداء الحكومي',
      section: 'قسم التقارير',
      automationLevel: 'مؤتمتة جزئياً',
      automationPct: 40,
      automationSystem: 'نظام إدارة الأداء',
      usageIntensity: '5',
      importance: '5',
      readinessLevel: '4',
      impactScore: '5',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الأولى - نوفمبر',
      outputClarity: '4',
      riskLevel: 'منخفض',
      transformYes: 'نعم',
      progress: 30,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd7',
      wf: 'ent1',
      type: 'operation',
      title: 'تحليل اتجاهات السياسات الصحية',
      desc: 'تحليل آلي لاتجاهات السياسات الصحية ومقارنتها بالممارسات العالمية.',
      path: 'strategy',
      entity: 'وزارة الصحة ووقاية المجتمع',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      axis: 'السياسات',
      subActivities: 'رصد السياسات المستجدة\nتحليل الأثر التشريعي',
      sector: 'قطاع السياسات الصحية',
      dept: 'إدارة السياسات العامة',
      section: 'قسم الدراسات',
      automationLevel: 'غير مؤتمتة',
      automationPct: 0,
      automationSystem: 'لا يوجد',
      usageIntensity: '3',
      importance: '4',
      readinessLevel: '3',
      impactScore: '4',
      transformScore: 'قابل جزئياً',
      transformPeriod: 'الدفعة الثالثة - مارس',
      outputClarity: '3',
      riskLevel: 'متوسط',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمدة قيد التنفيذ — الدفعة الثانية
    {
      id: 'd8',
      wf: 'exec',
      type: 'operation',
      title: 'رصد مؤشرات التنافسية العالمية',
      desc: 'رصد وتحليل مواقع الدولة في مؤشرات التنافسية العالمية آلياً.',
      path: 'strategy',
      entity: 'وزارة الاقتصاد والسياحة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      axis: 'التنافسية',
      subActivities: 'جمع بيانات المؤشرات الدولية\nتحليل الفجوات\nاقتراح مبادرات التحسين',
      sector: 'قطاع الاقتصاد',
      dept: 'إدارة التنافسية',
      section: 'قسم المؤشرات',
      automationLevel: 'مؤتمتة جزئياً',
      automationPct: 35,
      automationSystem: 'منصة المؤشرات الوطنية',
      usageIntensity: '4',
      importance: '5',
      readinessLevel: '4',
      impactScore: '4',
      transformScore: 'قابل كلياً',
      transformPeriod: 'الدفعة الثانية - فبراير',
      outputClarity: '4',
      riskLevel: 'منخفض',
      transformYes: 'نعم',
      progress: 20,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة — غير قابلة للتحول (لا تنطبق عليها فترة التحويل)
    {
      id: 'd9',
      wf: 'draft',
      type: 'operation',
      title: 'مراجعة الالتزامات المناخية الدولية',
      desc: 'مراجعة دورية للالتزامات المناخية ومواءمتها مع الاتفاقيات الدولية.',
      path: 'strategy',
      entity: 'وزارة التغير المناخي والبيئة',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      axis: 'السياسات',
      subActivities: 'حصر الالتزامات\nمراجعة الاتفاقيات',
      sector: 'قطاع التغير المناخي',
      dept: 'إدارة الاتفاقيات الدولية',
      section: 'قسم الالتزامات',
      automationLevel: 'غير مؤتمتة',
      automationPct: 0,
      automationSystem: 'لا يوجد',
      usageIntensity: '2',
      importance: '3',
      readinessLevel: '2',
      impactScore: '2',
      transformScore: 'غير قابل',
      outputClarity: '2',
      riskLevel: 'عالي',
      transformYes: 'لا',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار الخدمات الحكومية ══════════════

    // معتمدة قيد التنفيذ ضمن خطة إطلاق الدفعة الأولى
    {
      id: 'd10',
      wf: 'exec',
      type: 'service',
      title: 'خدمة تجديد الرخص التجارية الذكية',
      desc: 'تجديد فوري للرخص التجارية عبر مساعد محادثة ذكي.',
      path: 'services',
      entity: 'وزارة الاقتصاد والسياحة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      complexity: 'منخفض',
      subService: 'تجديد رخصة تجارية فورية',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الاقتصاد',
      dept: 'إدارة التسجيل التجاري',
      section: 'قسم الرخص',
      progress: 45,
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp1'],
      endDate: '2026-11-30',
      phases: [],
      launches: [
        {
          title: 'إطلاق الخدمات الاستباقية',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-11-25',
          desc: 'إطلاق الدفعة الأولى من الخدمات الاستباقية للجمهور.',
          status: 'مخطط',
          done: false,
          shared: true,
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام المساعد', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'لم تبدأ', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'لم تبدأ', newDate: '', reason: '' },
      ],
      links: [],
    },

    // معتمدة قيد التنفيذ — الخطة المشتركة نفسها
    {
      id: 'd11',
      wf: 'exec',
      type: 'service',
      title: 'منصة الخدمات الاستباقية',
      desc: 'تقديم الخدمات الحكومية استباقياً بناءً على أحداث حياة المتعامل.',
      path: 'services',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      complexity: 'منخفض',
      subService: 'إشعارات استباقية لأحداث الحياة',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات الحكومية',
      dept: 'إدارة الخدمات الرقمية',
      section: 'قسم تجربة المتعامل',
      progress: 35,
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp1'],
      endDate: '2026-12-20',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مكتملة + مموّلة من اللجنة (تُظهر الترشيح والتمويل والإطلاق المنجز)
    {
      id: 'd12',
      wf: 'exec',
      type: 'service',
      title: 'خدمة الاستعلام الذكي الموحّد',
      desc: 'مساعد محادثة موحّد للاستعلام عن حالة الطلبات عبر القنوات.',
      path: 'services',
      entity: 'وزارة المالية',
      approval: 'معتمد',
      status: 'مكتمل',
      complexity: 'متوسط',
      subService: 'الاستعلام عن حالة الطلب',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'مرتفع',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات المؤسسية',
      dept: 'إدارة خدمة المتعاملين',
      section: 'قسم القنوات الرقمية',
      progress: 100,
      budget: '1,500,000 درهم',
      scopeOfWork: 'بناء المساعد الموحّد وربطه بأنظمة الطلبات عبر القنوات الرقمية.',
      execBatch: 'إطلاق الدفعة الأولى',
      launchPlanIds: ['lp5'],
      endDate: '2026-09-15',
      nom: {
        by: 'فريق عمل المسار في المشروع',
        role: 'فريق عمل المسار في المشروع',
        path: 'services',
        at: T('2026-06-20T09:00:00'),
      },
      funded: { by: 'اللجنة الوطنية', at: T('2026-06-25T13:30:00'), direct: false },
      phases: [],
      launches: [
        {
          title: 'إطلاق الاستعلام الذكي',
          ltype: 'إطلاق منتج / خدمة',
          date: '2026-09-10',
          desc: '',
          status: 'تم الإطلاق',
          done: true,
          doneAt: T('2026-09-10T10:00:00'),
        },
      ],
      execChecklist: [
        { key: 'agents', label: 'بناء النظام المساعد', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'testing', label: 'الاختبار وضمان الجودة', status: 'مكتمل', newDate: '', reason: '' },
        { key: 'pilot', label: 'الإطلاق', status: 'مكتمل', newDate: '', reason: '' },
      ],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd13',
      wf: 'ent1',
      type: 'service',
      title: 'إصدار شهادة حسن السيرة والسلوك الفوري',
      desc: 'إصدار فوري للشهادة بعد التحقق الآلي من السجلات.',
      path: 'services',
      entity: 'وزارة الداخلية',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      complexity: 'متوسط',
      subService: 'إصدار شهادة حسن السيرة والسلوك',
      usageIntensity: 'مرتفعة',
      readinessLevel: 'متوسط',
      transformYes: 'نعم',
      sector: 'قطاع الخدمات الأمنية',
      dept: 'إدارة الأدلة الجنائية',
      section: 'قسم الشهادات',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // مسودة مُعادة بملاحظات
    {
      id: 'd14',
      wf: 'draft',
      type: 'service',
      title: 'معادلة الشهادات الدراسية الذكية',
      desc: 'معادلة آلية للشهادات الدراسية الصادرة من الخارج.',
      ret: {
        type: 'info',
        from: 'فريق عمل المسار في المشروع',
        note: 'يرجى إرفاق حجم الطلبات السنوي وقائمة الجهات التعليمية المعتمدة.',
        gate: 'priority',
      },
      path: 'services',
      entity: 'وزارة التربية والتعليم',
      approval: 'مسودة',
      status: 'لم يبدأ بعد',
      complexity: 'مرتفع',
      subService: 'معادلة شهادة دراسية',
      usageIntensity: 'متوسطة',
      readinessLevel: 'متوسط',
      transformYes: 'نعم',
      sector: 'قطاع التعليم',
      dept: 'إدارة المعادلات',
      section: 'قسم الشهادات الأجنبية',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار بناء القدرات والتدريب ══════════════

    // معتمد قيد التنفيذ
    {
      id: 'd15',
      wf: 'exec',
      type: 'operation',
      title: 'برنامج قيادات الذكاء الاصطناعي المساعد',
      desc: 'تأهيل القيادات الحكومية على توظيف المساعدين الذكيين في اتخاذ القرار.',
      path: 'capacity',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تصميم الحقائب التدريبية\nتنفيذ الورش القيادية\nقياس أثر التدريب',
      sector: 'قطاع تنمية القدرات',
      dept: 'إدارة التدريب الحكومي',
      section: 'قسم البرامج القيادية',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 55,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد ممثل الجهة
    {
      id: 'd16',
      wf: 'ent1',
      type: 'operation',
      title: 'تأهيل منسقي الجهات على أدوات المساعدين',
      desc: 'برنامج تدريبي عملي لمنسقي المسارات على بناء المساعدين واستخدامهم.',
      path: 'capacity',
      entity: 'وزارة الموارد البشرية والتوطين',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      subActivities: 'تحديد الفئات المستهدفة\nتنفيذ المعسكرات التدريبية\nإصدار الشهادات',
      sector: 'قطاع تنمية الموارد البشرية',
      dept: 'إدارة التدريب والتطوير',
      section: 'قسم البرامج التقنية',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'منخفض',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمد قيد التنفيذ — جهة أكاديمية
    {
      id: 'd17',
      wf: 'exec',
      type: 'operation',
      title: 'مختبر تطبيقات المساعدين الجامعي',
      desc: 'مختبر تطبيقي لتدريب الطلبة على بناء حالات استخدام حكومية حقيقية.',
      path: 'capacity',
      entity: 'جامعة الإمارات العربية المتحدة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تجهيز بيئة المختبر\nبناء الشراكات مع الجهات\nتشغيل الدفعة الأولى من المشاريع',
      sector: 'قطاع التعليم العالي',
      dept: 'كلية تقنية المعلومات',
      section: 'قسم الذكاء الاصطناعي',
      usageIntensity: 'منخفضة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 25,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // ══════════════ مسار تقنيات الذكاء الاصطناعي والبيانات ══════════════

    // معتمد قيد التنفيذ — بنية تحتية وطنية
    {
      id: 'd18',
      wf: 'exec',
      type: 'operation',
      title: 'المنصة الوطنية للنماذج اللغوية الحكومية',
      desc: 'بنية موحّدة لاستضافة النماذج اللغوية وتشغيل مساعدي الجهات عليها.',
      path: 'tech',
      entity: 'وزارة شؤون مجلس الوزراء',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'تجهيز البنية السحابية\nربط الجهات بالمنصة\nتفعيل ضوابط الاستخدام',
      sector: 'قطاع التقنيات الحكومية',
      dept: 'إدارة المنصات الوطنية',
      section: 'قسم الذكاء الاصطناعي',
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة 80% فأكثر',
      impactScore: 'عالي',
      complexity: 'مرتفع',
      transformYes: 'نعم',
      progress: 40,
      execBatch: 'إطلاق الدفعة الأولى',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // بانتظار اعتماد فريق عمل المسار
    {
      id: 'd19',
      wf: 'ent1',
      type: 'operation',
      title: 'إطار حوكمة بيانات المساعدين',
      desc: 'إطار موحّد لتصنيف البيانات وضوابط وصول المساعدين الذكيين إليها.',
      path: 'tech',
      entity: 'مصرف الإمارات العربية المتحدة المركزي',
      approval: 'تم الإرسال',
      status: 'لم يبدأ بعد',
      subActivities: 'تصنيف مستويات البيانات\nصياغة ضوابط الوصول\nاعتماد الإطار ونشره',
      sector: 'قطاع الرقابة المالية',
      dept: 'إدارة أمن المعلومات',
      section: 'قسم حوكمة البيانات',
      usageIntensity: 'متوسطة التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'عالي',
      complexity: 'مرتفع',
      transformYes: 'نعم',
      progress: 0,
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },

    // معتمد قيد التنفيذ
    {
      id: 'd20',
      wf: 'exec',
      type: 'operation',
      title: 'مصنّف الوثائق الصناعية الآلي',
      desc: 'نموذج لتصنيف واستخلاص بيانات الوثائق الصناعية والتراخيص آلياً.',
      path: 'tech',
      entity: 'وزارة الصناعة والتكنولوجيا المتقدمة',
      approval: 'معتمد',
      status: 'قيد التنفيذ',
      subActivities: 'بناء مجموعة البيانات\nتدريب النموذج\nالربط بنظام التراخيص',
      sector: 'قطاع الصناعة',
      dept: 'إدارة التحول الرقمي',
      section: 'قسم البيانات',
      usageIntensity: 'عالية التكرار',
      readinessLevel: 'جاهزة للتحول بنسبة بين 50% إلى 80%',
      impactScore: 'متوسط',
      complexity: 'متوسط',
      transformYes: 'نعم',
      progress: 15,
      execBatch: 'إطلاق الدفعة الثانية',
      phases: [],
      launches: [],
      execChecklist: [],
      links: [],
    },
  ];
}

function demoLaunchPlans(): LaunchPlan[] {
  return [
    {
      id: 'lp1',
      batch: 'إطلاق الدفعة الأولى',
      title: 'إطلاق الخدمات الاستباقية',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-11-25',
      desc: 'إطلاق الدفعة الأولى من الخدمات الاستباقية للجمهور.',
      scope: 'تحويل مجموعة الخدمات الاستباقية الأولى وربطها بمحرك أحداث الحياة.',
      budget: '3,500,000 درهم',
      launchBudget: '450,000 درهم',
    },
    {
      id: 'lp2',
      batch: 'إطلاق الدفعة الثانية',
      title: 'حزمة خدمات المتعاملين الثانية',
      ltype: 'إعلان رسمي',
      date: '2027-01-20',
      desc: '',
      scope: 'إطلاق الحزمة الثانية من خدمات المتعاملين المحوّلة على مستوى الجهات.',
      budget: '2,200,000 درهم',
      launchBudget: '180,000 درهم',
    },
    {
      id: 'lp5',
      batch: 'إطلاق الدفعة الأولى',
      title: 'إطلاق الاستعلام الذكي',
      ltype: 'إطلاق منتج / خدمة',
      date: '2026-09-10',
      desc: '',
      scope: 'إطلاق مساعد الاستعلام الموحّد عبر القنوات.',
      budget: '1,500,000 درهم',
      launchBudget: '120,000 درهم',
    },
  ];
}

// ════════════════════════════════════════════════════════════════════════════
// المشاريع الاستراتيجية — مشاريع معرّفة من اللجنة الوطنية ونماذج أعضائها
// ════════════════════════════════════════════════════════════════════════════
export function seedProjDefs(): ProjDef[] {
  if (!DEMO_DATA) return [];
  return [
    { id: 'pj1', name: 'المنصة الوطنية للمساعدين الحكوميين', lead: 'معالي عمر العلماء', member: 'سارة عبدالله الحوسني', start: '2026-06-01', end: '2027-05-31' },
    { id: 'pj2', name: 'مساعد المتعاملين الحكومي الموحّد', lead: 'سعادة محمد بن طليعة', member: 'خالد سالم النعيمي', start: '2026-08-01', end: '2027-02-28' },
    { id: 'pj3', name: 'منظومة البيانات الحكومية للذكاء الاصطناعي', lead: 'سعادة هيثم الريس', member: '', start: '2026-09-01', end: '2027-08-31' },
  ];
}

export function seedProjForms(): ProjForm[] {
  if (!DEMO_DATA) return [];
  return [
    // نموذج معتمد من اللجنة الوطنية — يعرض دورة الاعتماد كاملة
    {
      id: 'pf1',
      projId: 'pj1',
      owner: 'سارة عبدالله الحوسني',
      entityResp: 'وزارة شؤون مجلس الوزراء',
      desc: 'بناء منصة موحّدة لاستضافة المساعدين الحكوميين وربطها بأنظمة الجهات الاتحادية، مع ضوابط الحوكمة والاستخدام المعتمدة.',
      outputs: ['منصة تشغيل موحّدة للمساعدين', 'دليل ربط الجهات الاتحادية', 'إطار حوكمة الاستخدام'],
      phases: [
        { name: 'التأسيس والتصميم', start: '2026-06-01', end: '2026-08-31' },
        { name: 'التطوير والربط التجريبي', start: '2026-09-01', end: '2027-01-31' },
        { name: 'الإطلاق والتوسع', start: '2027-02-01', end: '2027-05-31' },
      ],
      team: [
        { name: 'سارة عبدالله الحوسني', title: 'رئيسة فريق المشروع', entity: 'وزارة شؤون مجلس الوزراء', email: 'sara.alhosani@moca.gov.ae', phone: '0501000001' },
        { name: 'محمد راشد الشحي', title: 'مهندس الحلول', entity: 'هيئة تنظيم الاتصالات والحكومة الرقمية', email: 'mohammed.alshehhi@tdra.gov.ae', phone: '0501000002' },
        { name: 'موزة أحمد الظاهري', title: 'مسؤولة الحوكمة', entity: 'وزارة شؤون مجلس الوزراء', email: 'moza.aldhaheri@moca.gov.ae', phone: '0501000003' },
      ],
      wf: 'approved',
      ret: null,
      log: [
        { action: 'submit', by: 'سارة عبدالله الحوسني', role: 'أعضاء المشاريع الاستراتيجية', at: T('2026-07-02T10:00:00'), note: 'أُرسل لاعتماد اللجنة الوطنية' },
        { action: 'approve', by: 'اللجنة الوطنية', role: 'اللجنة الوطنية للذكاء الاصطناعي المساعد', at: T('2026-07-09T13:00:00'), note: '' },
      ],
    },
    // نموذج مُرسل بانتظار اعتماد اللجنة الوطنية
    {
      id: 'pf2',
      projId: 'pj2',
      owner: 'خالد سالم النعيمي',
      entityResp: 'هيئة تنظيم الاتصالات والحكومة الرقمية',
      desc: 'مساعد محادثة موحّد للمتعاملين يغطي الخدمات الاتحادية الأكثر استخداماً ويحوّل الطلبات للجهات المعنية.',
      outputs: ['مساعد محادثة موحّد عبر القنوات', 'لوحة متابعة رضا المتعاملين'],
      phases: [
        { name: 'تحديد الخدمات ذات الأولوية', start: '2026-08-01', end: '2026-09-30' },
        { name: 'البناء والتجربة', start: '2026-10-01', end: '2026-12-31' },
        { name: 'الإطلاق التدريجي', start: '2027-01-01', end: '2027-02-28' },
      ],
      team: [
        { name: 'خالد سالم النعيمي', title: 'رئيس فريق المشروع', entity: 'هيئة تنظيم الاتصالات والحكومة الرقمية', email: 'khaled.alnuaimi@tdra.gov.ae', phone: '0501000004' },
        { name: 'فاطمة علي المرزوقي', title: 'مصممة تجربة المتعامل', entity: 'وزارة شؤون مجلس الوزراء', email: 'fatima.almarzooqi@moca.gov.ae', phone: '0501000005' },
      ],
      wf: 'sent',
      ret: null,
      log: [
        { action: 'submit', by: 'خالد سالم النعيمي', role: 'أعضاء المشاريع الاستراتيجية', at: T('2026-08-28T09:30:00'), note: 'أُرسل لاعتماد اللجنة الوطنية' },
      ],
    },
  ];
}

// ════════════════════════════════════════════════════════════════════════════
// سجل التغييرات — أثر النشاط الأخير على المدخلات المزروعة
// ════════════════════════════════════════════════════════════════════════════
export function seedChangeLog(): SeedChangeLogEntry[] {
  if (!DEMO_DATA) return [];
  return [
    { at: T('2026-08-30T11:40:00'), by: 'اللجنة الوطنية', role: 'اللجنة الوطنية للذكاء الاصطناعي المساعد', action: 'اعتماد نموذج مشروع استراتيجي', target: 'المنصة الوطنية للمساعدين الحكوميين', note: '' },
    { at: T('2026-08-31T09:15:00'), by: 'فريق عمل المسار في المشروع', role: 'فريق عمل المسار في المشروع', action: 'اعتماد مدخل', target: 'معالجة طلبات الدعم الفني', note: 'إلى مرحلة التنفيذ' },
    { at: T('2026-08-31T09:20:00'), by: 'فريق عمل المسار في المشروع', role: 'فريق عمل المسار في المشروع', action: 'إعادة بملاحظات', target: 'تدقيق طلبات الإجازات والبدلات', note: 'يرجى تحديد الأنظمة المرتبطة' },
    { at: T('2026-09-01T10:05:00'), by: 'منسق المسار في الجهة الاتحادية', role: 'منسق المسار في الجهة الاتحادية', action: 'إرسال مدخل للاعتماد', target: 'التصنيف الآلي للمعاملات الواردة', note: 'وزارة الطاقة والبنية التحتية' },
    { at: T('2026-09-01T14:30:00'), by: 'فريق عمل المسار في المشروع', role: 'فريق عمل المسار في المشروع', action: 'اعتماد مدخل', target: 'المنصة الوطنية للنماذج اللغوية الحكومية', note: 'إلى مرحلة التنفيذ' },
    { at: T('2026-09-02T08:45:00'), by: 'منسق المسار في الجهة الاتحادية', role: 'منسق المسار في الجهة الاتحادية', action: 'إرسال مدخل للاعتماد', target: 'تأهيل منسقي الجهات على أدوات المساعدين', note: 'وزارة الموارد البشرية والتوطين' },
  ];
}

// ════════════════════════════════════════════════════════════════════════════
// نسخة وزارة شؤون مجلس الوزراء — مدخلات الوحدات وحالات الاستخدام
// ════════════════════════════════════════════════════════════════════════════
export function seedMocaEntries(): MocaEntry[] {
  if (!DEMO_DATA) return [];
  const base = {
    outputs: '',
    beneficiary: '',
    specialization: 'تخصصية',
    dept: '',
    section: '',
    automationPct: '0',
    automationSystem: '',
    usageIntensity: 'متوسطة',
    frequency: 'شهرياً',
    duration: 'يومان',
    transformability: 'قابل كلياً',
    readiness: 'الجاهزية للتحول بنسبة بين 50% إلى 80%',
    priority: 'نعم',
    impact: 'عالي',
    complexity: 'متوسط',
    notes: '',
  };
  return [
    // معتمد وموزّع على الدفعة الأولى (توزيع معتمد)
    {
      ...base,
      id: 'mc1',
      unitId: 'sg',
      unitSector: '',
      wf: 'approved',
      ret: null,
      createdAt: '2026-07-20T09:00:00.000Z',
      submittedAt: '2026-07-22T10:00:00.000Z',
      decidedAt: '2026-07-28T12:00:00.000Z',
      mainProcess: 'إعداد جدول أعمال مجلس الوزراء',
      subProcess: 'تجهيز ملفات العرض والملخصات التنفيذية',
      outputs: 'ملخصات تنفيذية جاهزة للعرض على المجلس',
      beneficiary: 'أعضاء مجلس الوزراء',
      sector: 'الأمانة العامة لمجلس الوزراء',
      dept: 'إدارة شؤون المجلس',
      section: 'قسم جدول الأعمال',
      automationPct: '45',
      automationSystem: 'نظام إدارة الاجتماعات',
      usageIntensity: 'عالية',
      frequency: 'أسبوعياً',
      duration: '3 أيام',
      execBatch: 'إطلاق الدفعة الأولى',
      startDate: '2026-09-01',
      endDate: '2026-11-15',
      batchWf: 'approved',
    },
    // قيد اعتماد اللجنة الوطنية
    {
      ...base,
      id: 'mc2',
      unitId: 'sg',
      unitSector: '',
      wf: 'pending',
      ret: null,
      createdAt: '2026-08-18T09:00:00.000Z',
      submittedAt: '2026-08-25T11:00:00.000Z',
      mainProcess: 'متابعة تنفيذ قرارات المجلس',
      subProcess: 'إعداد تقارير حالة التنفيذ للجهات',
      outputs: 'تقرير دوري بحالة تنفيذ القرارات',
      beneficiary: 'الأمانة العامة والجهات الاتحادية',
      sector: 'الأمانة العامة لمجلس الوزراء',
      dept: 'إدارة المتابعة',
      section: 'قسم التقارير',
      automationPct: '30',
      automationSystem: 'نظام متابعة القرارات',
      transformability: 'قابل جزئياً',
      impact: 'متوسط',
    },
    // معتمد — توزيعه على الدفعة الثانية قيد اعتماد اللجنة
    {
      ...base,
      id: 'mc3',
      unitId: 'pmo',
      unitSector: 'قطاع الأداء والتميز الحكومي',
      wf: 'approved',
      ret: null,
      createdAt: '2026-07-25T09:00:00.000Z',
      submittedAt: '2026-08-01T10:00:00.000Z',
      decidedAt: '2026-08-06T13:00:00.000Z',
      mainProcess: 'إدارة منظومة الأداء الحكومي',
      subProcess: 'تحليل نتائج مؤشرات الأداء الاستراتيجية',
      outputs: 'تحليلات وتوصيات تحسين الأداء',
      beneficiary: 'قيادات الجهات الاتحادية',
      sector: 'قطاع الأداء والتميز الحكومي',
      dept: 'إدارة الأداء الحكومي',
      section: 'قسم التحليل',
      automationPct: '55',
      automationSystem: 'نظام أداء',
      usageIntensity: 'عالية',
      frequency: 'ربع سنوي',
      duration: 'أسبوع',
      execBatch: 'إطلاق الدفعة الثانية',
      startDate: '2026-12-05',
      endDate: '2027-02-20',
      batchWf: 'pending',
    },
    // مسودة لدى منسق المكتب الإعلامي
    {
      ...base,
      id: 'mc4',
      unitId: 'media',
      unitSector: '',
      wf: 'draft',
      ret: null,
      createdAt: '2026-08-30T09:00:00.000Z',
      mainProcess: 'إدارة المحتوى الإعلامي الحكومي',
      subProcess: 'إعداد الملخصات الإخبارية اليومية',
      outputs: 'ملخص إخباري يومي للقيادات',
      beneficiary: 'القيادات الحكومية',
      sector: 'المكتب الإعلامي لحكومة دولة الإمارات',
      dept: 'إدارة الرصد الإعلامي',
      section: 'قسم التحرير',
      automationPct: '20',
      usageIntensity: 'عالية',
      frequency: 'يومياً',
      duration: '4 ساعات',
    },
    // معتمد بانتظار التوزيع على دفعة
    {
      ...base,
      id: 'mc5',
      unitId: 'fcsc',
      unitSector: '',
      wf: 'approved',
      ret: null,
      createdAt: '2026-08-05T09:00:00.000Z',
      submittedAt: '2026-08-10T10:00:00.000Z',
      decidedAt: '2026-08-17T09:30:00.000Z',
      mainProcess: 'إصدار الإحصاءات الوطنية',
      subProcess: 'تدقيق جداول البيانات قبل النشر',
      outputs: 'جداول إحصائية مدققة وجاهزة للنشر',
      beneficiary: 'الجهات الحكومية والباحثون',
      sector: 'المركز الاتحادي للتنافسية والإحصاء',
      dept: 'إدارة الإحصاءات',
      section: 'قسم ضبط الجودة',
      automationPct: '60',
      automationSystem: 'المنصة الإحصائية الوطنية',
      usageIntensity: 'عالية',
      frequency: 'شهرياً',
      duration: 'يومان',
    },
    // مسودة مُعادة بملاحظات اللجنة (للتعديل)
    {
      ...base,
      id: 'mc6',
      unitId: 'knowledge',
      unitSector: '',
      wf: 'draft',
      ret: { type: 'info', note: 'يرجى توضيح حجم الطلبات السنوي والأنظمة المرتبطة.', at: '2026-08-27T12:00:00.000Z' },
      createdAt: '2026-08-12T09:00:00.000Z',
      submittedAt: '2026-08-20T10:00:00.000Z',
      mainProcess: 'إدارة برامج التبادل المعرفي',
      subProcess: 'مطابقة طلبات الحكومات الشريكة مع الخبرات',
      outputs: 'خطة تبادل معرفي لكل شراكة',
      beneficiary: 'الحكومات الشريكة',
      sector: 'مكتب التبادل المعرفي الحكومي',
      dept: 'إدارة الشراكات',
      section: 'قسم البرامج',
      automationPct: '10',
      transformability: 'قابل جزئياً',
      impact: 'متوسط',
      complexity: 'منخفض',
    },

    // ── مكتب رئاسة مجلس الوزراء — بقية القطاعات ──
    // معتمد بانتظار التوزيع على دفعة
    {
      ...base,
      id: 'mc7',
      unitId: 'pmo',
      unitSector: 'قطاع الاستراتيجية والابتكار',
      wf: 'approved',
      ret: null,
      createdAt: '2026-08-02T09:00:00.000Z',
      submittedAt: '2026-08-06T10:00:00.000Z',
      decidedAt: '2026-08-12T11:00:00.000Z',
      mainProcess: 'إعداد الاستراتيجيات الوطنية',
      subProcess: 'مواءمة مبادرات الجهات مع الأجندة الوطنية',
      outputs: 'مصفوفة مواءمة المبادرات مع الأهداف الوطنية',
      beneficiary: 'الجهات الاتحادية',
      sector: 'قطاع الاستراتيجية والابتكار',
      dept: 'إدارة الاستراتيجية',
      section: 'قسم المواءمة',
      automationPct: '25',
      automationSystem: 'منصة الأجندة الوطنية',
      usageIntensity: 'عالية',
      frequency: 'سنوياً',
      duration: 'أسبوعان',
    },
    // معتمد وموزّع على الدفعة الثالثة (توزيع معتمد)
    {
      ...base,
      id: 'mc8',
      unitId: 'pmo',
      unitSector: 'قطاع الخدمات الحكومية',
      wf: 'approved',
      ret: null,
      createdAt: '2026-07-28T09:00:00.000Z',
      submittedAt: '2026-08-03T10:00:00.000Z',
      decidedAt: '2026-08-09T12:30:00.000Z',
      mainProcess: 'تقييم الخدمات الحكومية',
      subProcess: 'تحليل ملاحظات المتعاملين على الخدمات',
      outputs: 'تقرير تحليل تجربة المتعامل بالتوصيات',
      beneficiary: 'الجهات مقدمة الخدمات',
      sector: 'قطاع الخدمات الحكومية',
      dept: 'إدارة تجربة المتعامل',
      section: 'قسم التحليل',
      automationPct: '50',
      automationSystem: 'منصة تجربة المتعامل',
      usageIntensity: 'عالية',
      frequency: 'شهرياً',
      duration: '3 أيام',
      execBatch: 'إطلاق الدفعة الثالثة',
      startDate: '2027-03-10',
      endDate: '2027-05-20',
      batchWf: 'approved',
    },
    // قيد اعتماد اللجنة الوطنية
    {
      ...base,
      id: 'mc9',
      unitId: 'pmo',
      unitSector: 'قطاع العلاقات الدولية',
      wf: 'pending',
      ret: null,
      createdAt: '2026-08-20T09:00:00.000Z',
      submittedAt: '2026-08-27T10:00:00.000Z',
      mainProcess: 'إدارة الاتفاقيات والزيارات الدولية',
      subProcess: 'إعداد ملفات الزيارات الرسمية',
      outputs: 'ملف تعريفي متكامل لكل زيارة',
      beneficiary: 'القيادات والوفود الرسمية',
      sector: 'قطاع العلاقات الدولية',
      dept: 'إدارة العلاقات الدولية',
      section: 'قسم البروتوكول',
      automationPct: '15',
      usageIntensity: 'متوسطة',
      frequency: 'شهرياً',
      duration: 'أسبوع',
      transformability: 'قابل جزئياً',
      readiness: 'الجاهزية للتحول بنسبة بين 30% إلى 50%',
      impact: 'متوسط',
    },
    // مسودة لدى المنسق
    {
      ...base,
      id: 'mc10',
      unitId: 'pmo',
      unitSector: 'بناء القدرات وإدارة المواهب',
      wf: 'draft',
      ret: null,
      createdAt: '2026-08-29T09:00:00.000Z',
      mainProcess: 'إدارة برامج المواهب الحكومية',
      subProcess: 'فرز طلبات الترشح للبرامج القيادية',
      outputs: 'قائمة مختصرة بالمرشحين المؤهلين',
      beneficiary: 'الموظفون الحكوميون',
      sector: 'بناء القدرات وإدارة المواهب',
      dept: 'إدارة المواهب',
      section: 'قسم الترشيح',
      automationPct: '35',
      automationSystem: 'نظام إدارة المواهب',
      usageIntensity: 'متوسطة',
      frequency: 'سنوياً',
      duration: '10 أيام',
    },
    // معتمد — توزيعه أُعيد بملاحظات اللجنة (يعود مسودةً للمنسق)
    {
      ...base,
      id: 'mc11',
      unitId: 'pmo',
      unitSector: 'القمة العالمية للحكومات',
      wf: 'approved',
      ret: null,
      createdAt: '2026-07-15T09:00:00.000Z',
      submittedAt: '2026-07-20T10:00:00.000Z',
      decidedAt: '2026-07-26T09:00:00.000Z',
      mainProcess: 'تنظيم القمة العالمية للحكومات',
      subProcess: 'إدارة تسجيل المشاركين والوفود',
      outputs: 'قاعدة بيانات المشاركين واعتماداتهم',
      beneficiary: 'المشاركون والوفود',
      sector: 'القمة العالمية للحكومات',
      dept: 'إدارة التسجيل',
      section: 'قسم الاعتماد',
      automationPct: '65',
      automationSystem: 'منصة تسجيل القمة',
      usageIntensity: 'عالية',
      frequency: 'سنوياً',
      duration: 'شهر',
      execBatch: 'إطلاق الدفعة الثانية',
      startDate: '2026-12-10',
      endDate: '2027-01-30',
      batchWf: 'draft',
      batchRet: 'info',
      batchNote: 'يرجى تأجيل التوزيع إلى ما بعد انعقاد القمة في فبراير.',
    },

    // ── بقية وحدات الوزارة ──
    // قيد اعتماد اللجنة الوطنية
    {
      ...base,
      id: 'mc12',
      unitId: 'future',
      unitSector: '',
      wf: 'pending',
      ret: null,
      createdAt: '2026-08-15T09:00:00.000Z',
      submittedAt: '2026-08-24T10:00:00.000Z',
      mainProcess: 'استشراف المستقبل الحكومي',
      subProcess: 'إعداد تقارير الاتجاهات المستقبلية',
      outputs: 'تقرير اتجاهات مستقبلية ربع سنوي',
      beneficiary: 'صنّاع القرار الحكومي',
      sector: 'مكتب التطوير الحكومي والمستقبل',
      dept: 'إدارة الاستشراف',
      section: 'قسم البحوث',
      automationPct: '20',
      usageIntensity: 'متوسطة',
      frequency: 'ربع سنوي',
      duration: 'أسبوعان',
    },
    // معتمد — توزيعه على الدفعة الأولى قيد اعتماد اللجنة
    {
      ...base,
      id: 'mc13',
      unitId: 'central',
      unitSector: '',
      wf: 'approved',
      ret: null,
      createdAt: '2026-07-30T09:00:00.000Z',
      submittedAt: '2026-08-04T10:00:00.000Z',
      decidedAt: '2026-08-10T11:00:00.000Z',
      mainProcess: 'إدارة المشتريات المركزية',
      subProcess: 'مطابقة عروض الموردين مع المواصفات',
      outputs: 'تقرير مطابقة العروض وتوصية الترسية',
      beneficiary: 'الإدارات الطالبة',
      sector: 'قطاع الخدمات المركزية',
      dept: 'إدارة المشتريات',
      section: 'قسم المناقصات',
      automationPct: '40',
      automationSystem: 'نظام المشتريات الحكومية',
      usageIntensity: 'عالية',
      frequency: 'أسبوعياً',
      duration: '5 أيام',
      execBatch: 'إطلاق الدفعة الأولى',
      startDate: '2026-10-01',
      endDate: '2026-11-25',
      batchWf: 'pending',
    },
    // مرفوض من اللجنة الوطنية (يعود للمنسق بسبب الرفض)
    {
      ...base,
      id: 'mc14',
      unitId: 'governance',
      unitSector: '',
      wf: 'draft',
      ret: { type: 'reject', note: 'العملية خاضعة لمتطلبات رقابية تمنع أتمتة القرار في هذه المرحلة.', at: '2026-08-26T10:30:00.000Z' },
      createdAt: '2026-08-10T09:00:00.000Z',
      submittedAt: '2026-08-19T10:00:00.000Z',
      mainProcess: 'الرقابة المالية على الجهات',
      subProcess: 'مراجعة التقارير المالية الربعية',
      outputs: 'ملاحظات الرقابة على التقارير المالية',
      beneficiary: 'الجهات الاتحادية',
      sector: 'قطاع الحوكمة والرقابة المالية',
      dept: 'إدارة الرقابة المالية',
      section: 'قسم المراجعة',
      automationPct: '30',
      automationSystem: 'النظام المالي الاتحادي',
      usageIntensity: 'متوسطة',
      frequency: 'ربع سنوي',
      duration: 'أسبوع',
      transformability: 'قابل جزئياً',
      complexity: 'عالي',
    },
    // معتمد بانتظار التوزيع على دفعة
    {
      ...base,
      id: 'mc15',
      unitId: 'dubai',
      unitSector: '',
      wf: 'approved',
      ret: null,
      createdAt: '2026-08-08T09:00:00.000Z',
      submittedAt: '2026-08-13T10:00:00.000Z',
      decidedAt: '2026-08-20T12:00:00.000Z',
      mainProcess: 'التنسيق مع حكومة دبي',
      subProcess: 'متابعة المبادرات المشتركة',
      outputs: 'تقرير متابعة دوري للمبادرات المشتركة',
      beneficiary: 'الجهات الاتحادية والمحلية',
      sector: 'المكتب التنفيذي - دبي',
      dept: 'إدارة التنسيق',
      section: 'قسم المتابعة',
      automationPct: '30',
      usageIntensity: 'متوسطة',
      frequency: 'شهرياً',
      duration: '3 أيام',
      impact: 'متوسط',
      complexity: 'منخفض',
    },
  ];
}

export function seedMocaUseCases(): MocaUseCase[] {
  if (!DEMO_DATA) return [];
  return [
    {
      id: 'muc1',
      unitId: 'sg',
      entryId: 'mc1',
      mainProcess: 'إعداد جدول أعمال مجلس الوزراء',
      subProcess: 'تجهيز ملفات العرض والملخصات التنفيذية',
      status: 'قيد التنفيذ',
      createdAt: '2026-09-05T09:00:00.000Z',
      updates: [
        { text: 'اكتمال تحليل المتطلبات وتحديد مصادر البيانات', vendor: 'الفريق التقني الداخلي', at: '2026-09-20T10:00:00.000Z' },
        { text: 'نموذج أولي للملخصات التنفيذية قيد المراجعة', vendor: 'شريك التطوير', at: '2026-10-14T09:30:00.000Z' },
      ],
    },
    {
      id: 'muc2',
      unitId: 'pmo',
      unitSector: 'قطاع الأداء والتميز الحكومي',
      entryId: 'mc3',
      mainProcess: 'إدارة منظومة الأداء الحكومي',
      subProcess: 'تحليل نتائج مؤشرات الأداء الاستراتيجية',
      status: 'لم تبدأ بعد',
      createdAt: '2026-09-10T09:00:00.000Z',
      updates: [],
    },
    {
      id: 'muc3',
      unitId: 'fcsc',
      entryId: 'mc5',
      mainProcess: 'إصدار الإحصاءات الوطنية',
      subProcess: 'تدقيق جداول البيانات قبل النشر',
      status: 'مكتملة',
      createdAt: '2026-08-20T09:00:00.000Z',
      updates: [
        { text: 'تشغيل مساعد التدقيق على إصدارات شهر أغسطس بنجاح', vendor: 'الفريق التقني الداخلي', at: '2026-08-31T11:00:00.000Z' },
      ],
    },
    {
      id: 'muc4',
      unitId: 'pmo',
      unitSector: 'قطاع الخدمات الحكومية',
      entryId: 'mc8',
      mainProcess: 'تقييم الخدمات الحكومية',
      subProcess: 'تحليل ملاحظات المتعاملين على الخدمات',
      status: 'قيد التنفيذ',
      createdAt: '2026-09-12T09:00:00.000Z',
      updates: [
        { text: 'ربط مصادر ملاحظات المتعاملين بالمساعد التحليلي', vendor: 'شريك التطوير', at: '2026-10-02T10:00:00.000Z' },
      ],
    },
  ];
}
